# This is a basic workflow to help you get started with Actions

name: Zmindmap-mobile-Mobile-CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2 #nodejs 环境
        with:
          node-version: '14' #nodejs 版本
      - run: npm install #安装依赖
      - run: npm run build --if-present #打包

      - name: Tar dist file
        run: |
          tar -zcvf mindmap-mobile.tar.gz dist # 打包dist文件夹
      - name: Scp_upload_tar_file # 上传至服务器
        uses: garygrossgarten/github-action-scp@release
        with:
          local: 'mindmap-mobile.tar.gz'
          remote: '/www/wwwroot/mindmap-mobile.tar.gz'
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
      - name: Deploy_app_tar #解压压缩包
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /www/wwwroot/
            rm -rf mindmap-mobile
            tar -zxvf mindmap-mobile.tar.gz
            mv dist mindmap-mobile
            rm -rf mindmap-mobile.tar.gz
